### PR TITLE
Fix asset uploading

### PR DESCRIPTION
**Pull request by dowoge**
This is my (probably poorly implemented) fix for decal/mesh uploading, please feel free to comment or just directly edit the changes.

### CODE REVIEW

**Comment by Simoxus** [comment]
nice

**Comment by Azino39** [comment]
i dont have "source2roblox.exe" thing for some reason

**Comment by vanyils** [comment]
> i dont have "source2roblox.exe" thing for some reason

same

**Comment by Simoxus** [comment]
because you build it using Visual Studio, by the way im pretty sure this doesnt work anymore since oauth 2 was released onto Roblox

**Comment by throughthefog** [comment]
how long do i have to wait for asset upload cooldown to finish?

**Comment by dowoge** [comment]
For anyone seeing this, I would appreciate not being contacted about this. **_I will not provide support_** or explain how to fix any of it. Roblox changes the APIs often and it is a hassle to maintain.

**Pull request closed without merging**
